// WEB3 REDUCER
export const SET_WEB3_INSTANCE = 'SET_WEB3_INSTANCE';
export const ADD_WEB3_READONLY_INSTANCE = 'ADD_WEB3_READONLY_INSTANCE';
export const ADD_CONTRACT = 'ADD_CONTRACT';
export const REMOVE_CONTRACT = 'REMOVE_CONTRACT';
export const SET_INITIALIZED = 'SET_INITIALIZED';
export const SET_READONLY_INITIALIZED = 'SET_READONLY_INITIALIZED';

// WALLET REDUCER
export const SET_RROVIDER_WALLET = 'SET_RROVIDER_WALLET';
export const SET_CHAIN_ID = 'SET_CHAIN_ID';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS';
